import Head from "next/head";
import { useRef } from "react";
import Link from "next/link";
import { motion, useInView } from "framer-motion";
import Image from "next/image";
import Hero from "../assets/hero-image.png";
import First from "../assets/1.png";
import Second from "../assets/2.png";
import Third from "../assets/3.png";
import Plane from "../assets/Airplace-Icon.png";
import Tape from "../assets/taped-image.png";
import Exposure from "../assets/Exposure.png";
import Arrow from "../assets/Arrow.png";
import Fourth from "../assets/4.png";
import Sitting from "../assets/Sitting.png";
import Accordion from "../components/Accordion";

export default function Home() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });

  return (
    <div>
      <Head>
        <title>Travel - Scrapbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto max-w-6xl">
        <nav className="flex justify-between py-10 m-0">
          <ul className="flex space-x-16">
            <Link href="#">
              <li className="hover:font-bold cursor-pointer">Home</li>
            </Link>
            <Link href="#">
              <li className="hover:font-bold cursor-pointer">Guides</li>
            </Link>
            <Link href="#">
              <li className="hover:font-bold cursor-pointer">Flights</li>
            </Link>
            <Link href="#">
              <li className="hover:font-bold cursor-pointer">About</li>
            </Link>
          </ul>
          <div className="border-2 border-solid border-black py-1 px-8 rounded font-bold">
            <Link href="#">Contact Us</Link>
          </div>
        </nav>
        <section className="hero flex justify-between py-6 my-12">
          <motion.div
            className="w-2/5 pr-16 relative"
            ref={ref}
            style={{
              transform: isInView ? "none" : "translateX(-200px)",
              opacity: isInView ? 1 : 0,
              transition: "all 0.9s cubic-bezier(0.17, 0.55, 0.55, 1) 0.5s",
            }}
          >
            <h1 className='text-7xl font-["Cardo"] font-bold text-[#232323]'>
              Travel to
              <br />
              your dream
              <br />
              destination
            </h1>
            <p className='font-["Lato"] py-6 text-[#232323]'>
              Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis
              ipsum sus pendisse ultrices gravida.{" "}
            </p>
            <Link href="#">
              <p className='absolute bottom-2 py-2 px-8 text-[white] bg-[#232323] rounded w-[50%] text-center font-["Lato"] font-bold'>
                Reserve Ticket
              </p>
            </Link>
          </motion.div>
          <motion.div
            initial={{ translateX: 100 }}
            whileInView={{ translateX: 0 }}
          >
            <Image src={Hero} alt="travel" />
          </motion.div>
        </section>
      </main>
      <section className="bg-[#232323] py-12 my-20">
        <div className="w-1/3 m-0 mx-auto">
          <h2 className='font-["Cardo"] text-[#e9e7e7] text-center font-bold text-5xl'>
            Create a memory to remember
          </h2>
          <p className="text-[#e9e7e7] text-center py-5 text-sm w-[70%] mx-auto block">
            Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do ei
            usmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum
            sus pendisse ultrices gravida.{" "}
          </p>
          <Link href="#">
            <button className='text-[#e9e7e7] py-1.5 px-12 rounded border-2 border-solid font-["Lato"] font-bold mt-4 mb-0 ml-auto mr-auto block'>
              My Travel Logs
            </button>
          </Link>
        </div>
      </section>
      <section>
        <div className="container mx-auto max-w-6xl flex justify-between py-20">
          <div className="w-4/12">
            <Image src={First} alt="" />
            <div className="h-1 bg-[#232323] w-10 mt-8 mb-8"></div>
            <h3 className="text-3xl w-[50%] font-['Cardo'] font-bold">
              Lorem ipsum dolor sit amet
            </h3>
            <p className="text-justify pr-6 font-['Lato']">
              Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do
              ei usmod tempor incididunt ut labore et dolore magna aliqua. Quis
              ipsum sus pendisse ultrices gravida.
            </p>
          </div>
          <div className="w-4/12">
            <Image src={Second} alt="" />
            <div className="h-1 bg-[#232323] w-10 mt-8 mb-8"></div>
            <h3 className="text-3xl w-[50%] font-['Cardo'] font-bold">
              Lorem ipsum dolor sit amet
            </h3>
            <p className="text-justify pr-6 font-['Lato']">
              Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do
              ei usmod tempor incididunt ut labore et dolore magna aliqua. Quis
              ipsum sus pendisse ultrices gravida.
            </p>
          </div>
          <div className="w-4/12">
            <Image src={Third} alt="" />
            <div className="h-1 bg-[#232323] w-10 mt-8 mb-8"></div>
            <h3 className="text-3xl w-[50%] font-['Cardo'] font-bold">
              Lorem ipsum dolor sit amet
            </h3>
            <p className="text-justify pr-6 font-['Lato']">
              Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do
              ei usmod tempor incididunt ut labore et dolore magna aliqua. Quis
              ipsum sus pendisse ultrices gravida.
            </p>
          </div>
        </div>
      </section>
      <section>
        <div className="container mx-auto max-w-6xl flex flex-col items-center mt-64">
          <div className="my-8">
            <Image src={Plane} alt="" />
          </div>
          <p className="text-8xl font-['Cardo'] font-bold text-center w-4/5 mt-10">
            See places you’ve{" "}
            <span className="italic underline font-['Cardo']">never</span> been
            before
          </p>
          <p className="text-center text-lg my-12">
            Lorem Ipsum Dolor | Lorem Ipsum Dolor | Lorem Ipsum Dolor
          </p>
        </div>
      </section>
      <section className="container mx-auto max-w-6xl">
        <div className="flex justify-between">
          <div className="w-[45%]">
            <Image src={Tape} alt="" />
          </div>
          <div className="w-[50%]">
            <Image src={Exposure} alt="" />
            <div className="w-[120%] flex justify-left my-10">
              <p className="font-bold underline text-4xl w-[40%] font-['Cardo'] leading-tight">
                Lorem ipsum dolor sit amet consectetur adipiscing elit sed do ei
              </p>
              <div className="w-[50%] ml-1">
                <p className="text-justify font-['Lato'] leading-5">
                  Lorem ipsum dolor sit amet, consectetur adip isicing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud.
                </p>
                <br />
                <p className="text-justify font-['Lato'] leading-5">
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo
                  consequat. Duis aute irure dolor in reprehenderit in voluptate
                  velit esse cillum dolore eu fugiat nulla pariatur.
                </p>
                <div className="text-right mt-12">
                  <Image src={Arrow} alt="" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-[#232323] py-32">
        <div className="container mx-auto max-w-6xl">
          <div className="text-[white] font-['Lato'] mx-auto">
            <div className="float-right pl-10 mr-[-50px]">
              <Image src={Fourth} alt="" />
            </div>
            <h2 className="font-['Cardo'] font-bold text-5xl">
              Choose anywhere you’d like to be
            </h2>
            <div className="mt-10">
              <h3 className="text-xl font-bold py-5">Lorem Ipsum dolor</h3>
              <p className="font-['Lato'] text-justify">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                ei usmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in repre henderit in voluptate velit esse.
              </p>
              <h3 className="text-xl font-bold py-5">Lorem Ipsum dolor</h3>
              <p className="font-['Lato'] text-justify">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                ei usmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in repre henderit in voluptate velit esse.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="py-28">
        <div className="container mx-auto max-w-6xl">
          <div className="float-right m-0">
            <Image src={Sitting} alt="" />
          </div>
          <div className="w-[60%]">
            <h2 className="font-['Cardo'] text-7xl font-bold">
              Lorem ipsum dolor sit amet consectetur
            </h2>
            <div className="m-0">
              <Accordion />
              <Accordion />
              <Accordion />
              <Accordion />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
