import Head from "next/head";
import { useRef } from "react";
import Link from "next/link";
import { motion, useInView } from "framer-motion";
import Image from "next/image";
import Hero from "../assets/hero-image.png";
import First from "../assets/1.png";
import Second from "../assets/2.png";
import Third from "../assets/3.png";
import Plane from "../assets/Airplace-Icon.png";
import Tape from "../assets/taped-image.png";
import Exposure from "../assets/Exposure.png";
import Arrow from "../assets/Arrow.png";
import Fourth from "../assets/4.png";
import Sitting from "../assets/Sitting.png";
import Accordion from "../components/Accordion";
import Testimonials from "../components/Testimonials";
import Form from "../assets/form-image.png";

export default function Home() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });

  return (
    <>
      <Head>
        <title>Travel - Scrapbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="container mx-auto block sm:max-w-6xl px-6">
        <nav className="flex sm:justify-between justify-center py-10">
          <ul className="flex space-x-16">
            <Link href="#">
              <li className="hover:font-bold cursor-pointer">Home</li>
            </Link>
            <Link href="#">
              <li className="hover:font-bold cursor-pointer">Guides</li>
            </Link>
            <Link href="#">
              <li className="hover:font-bold cursor-pointer">Flights</li>
            </Link>
            <Link href="#">
              <li className="hover:font-bold cursor-pointer">About</li>
            </Link>
          </ul>
          <div className="border-2 border-solid border-black py-1 px-8 rounded font-bold hidden sm:block">
            <Link href="#">Contact Us</Link>
          </div>
        </nav>
      </header>
      <section className="hero">
        <div className="flex flex-col md:flex-row items-center md:justify-between md:my-12 mx-auto max-w-6xl px-6">
        <motion.div
          className="md:w-[45%] relative"
          ref={ref}
          style={{
            transform: isInView ? "none" : "translateX(-200px)",
            opacity: isInView ? 1 : 0,
            transition: "all 0.9s cubic-bezier(0.17, 0.55, 0.55, 1) 0.5s",
          }}
        >
          <h1
            className='md:text-4xl lg:text-6xl font-["Cardo"] font-bold text-[#232323] text-4xl md:text-left text-center'
          >
            Travel to your dream destination
          </h1>
          <p className='font-["Lato"] py-6 lg:py-14 text-[#232323] text-[.8em] md:text-[1em] text-center md:text-left'>
            Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis
            ipsum sus pendisse ultrices gravida.{" "}
          </p>
          <Link href="#">
            <p className='md:relative lg:bottom-2 py-2 md:py8 px-8 text-[white] bg-[#232323] rounded w-[50%] md:text-[.8em] text-center font-["Lato"] font-bold block mx-auto my-4 md:inline-block'>
              Reserve Ticket
            </p>
          </Link>
        </motion.div>
        <motion.div
          initial={{ translateX: 100 }}
          whileInView={{ translateX: 0 }}
          className="w-[100%] md:w-[50%] block mx-0 my-auto"
        >
          <Image src={Hero} alt="travel" />
        </motion.div>
        </div>
      </section>
      <section className="bg-[#232323] py-12 my-20">
        <div className="w-1/3 m-0 mx-auto">
          <h2 className='font-["Cardo"] text-[#e9e7e7] text-center font-bold text-5xl'>
            Create a memory to remember
          </h2>
          <p className="text-[#e9e7e7] text-center py-5 text-sm w-[70%] mx-auto block">
            Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do ei
            usmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum
            sus pendisse ultrices gravida.{" "}
          </p>
          <Link href="#">
            <button className='text-[#e9e7e7] py-1.5 px-12 rounded border-2 border-solid font-["Lato"] font-bold mt-4 mb-0 ml-auto mr-auto block'>
              My Travel Logs
            </button>
          </Link>
        </div>
      </section>
      <section>
        <div className="container mx-auto max-w-6xl flex justify-between py-20">
          <div className="w-4/12">
            <Image src={First} alt="" />
            <div className="h-1 bg-[#232323] w-10 mt-8 mb-8"></div>
            <h3 className="text-3xl w-[50%] font-['Cardo'] font-bold">
              Lorem ipsum dolor sit amet
            </h3>
            <p className="text-justify pr-6 font-['Lato']">
              Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do
              ei usmod tempor incididunt ut labore et dolore magna aliqua. Quis
              ipsum sus pendisse ultrices gravida.
            </p>
          </div>
          <div className="w-4/12">
            <Image src={Second} alt="" />
            <div className="h-1 bg-[#232323] w-10 mt-8 mb-8"></div>
            <h3 className="text-3xl w-[50%] font-['Cardo'] font-bold">
              Lorem ipsum dolor sit amet
            </h3>
            <p className="text-justify pr-6 font-['Lato']">
              Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do
              ei usmod tempor incididunt ut labore et dolore magna aliqua. Quis
              ipsum sus pendisse ultrices gravida.
            </p>
          </div>
          <div className="w-4/12">
            <Image src={Third} alt="" />
            <div className="h-1 bg-[#232323] w-10 mt-8 mb-8"></div>
            <h3 className="text-3xl w-[50%] font-['Cardo'] font-bold">
              Lorem ipsum dolor sit amet
            </h3>
            <p className="text-justify pr-6 font-['Lato']">
              Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do
              ei usmod tempor incididunt ut labore et dolore magna aliqua. Quis
              ipsum sus pendisse ultrices gravida.
            </p>
          </div>
        </div>
      </section>
      <section>
        <div className="container mx-auto max-w-6xl flex flex-col items-center mt-64">
          <div className="my-8">
            <Image src={Plane} alt="" />
          </div>
          <p className="text-8xl font-['Cardo'] font-bold text-center w-4/5 mt-10">
            See places you’ve{" "}
            <span className="italic underline font-['Cardo']">never</span> been
            before
          </p>
          <p className="text-center text-lg my-12">
            Lorem Ipsum Dolor | Lorem Ipsum Dolor | Lorem Ipsum Dolor
          </p>
        </div>
      </section>
      <section className="container mx-auto max-w-6xl">
        <div className="flex justify-between">
          <div className="w-[45%]">
            <Image src={Tape} alt="" />
          </div>
          <div className="w-[50%]">
            <Image src={Exposure} alt="" />
            <div className="w-[100%] flex justify-left my-10">
              <p className="font-bold underline text-4xl w-[40%] font-['Cardo'] leading-tight">
                Lorem ipsum dolor sit amet consectetur adipiscing elit sed do ei
              </p>
              <div className="w-[50%] ml-1">
                <p className="text-justify font-['Lato'] leading-5">
                  Lorem ipsum dolor sit amet, consectetur adip isicing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud.
                </p>
                <br />
                <p className="text-justify font-['Lato'] leading-5">
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo
                  consequat. Duis aute irure dolor in reprehenderit in voluptate
                  velit esse cillum dolore eu fugiat nulla pariatur.
                </p>
                <div className="text-right mt-12">
                  <Image src={Arrow} alt="" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-[#232323] py-32">
        <div className="container mx-auto max-w-6xl">
          <div className="text-[white] font-['Lato'] mx-auto">
            <div className="float-right pl-10 mr-[0px] max-w-full">
              <Image src={Fourth} alt="" />
            </div>
            <h2 className="font-['Cardo'] font-bold text-5xl">
              Choose anywhere you’d like to be
            </h2>
            <div className="mt-10">
              <h3 className="text-xl font-bold py-5">Lorem Ipsum dolor</h3>
              <p className="font-['Lato'] text-justify">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                ei usmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in repre henderit in voluptate velit esse.
              </p>
              <h3 className="text-xl font-bold py-5">Lorem Ipsum dolor</h3>
              <p className="font-['Lato'] text-justify">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                ei usmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in repre henderit in voluptate velit esse.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="py-28">
        <div className="container mx-auto max-w-6xl">
          <div className="float-right m-0">
            <Image src={Sitting} alt="" />
          </div>
          <div className="w-[60%]">
            <h2 className="font-['Cardo'] text-7xl font-bold">
              Lorem ipsum dolor sit amet consectetur
            </h2>
            <div className="my-12">
              <Accordion />
              <Accordion />
              <Accordion />
              <Accordion />
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className="container mx-auto max-w-6xl my-8">
          <h1 className="font-['Cardo'] text-7xl font-bold w-[50%] text-center mx-auto">
            Here's what they have to say...
          </h1>
        </div>
        <Testimonials />
      </section>
      <section className="py-28">
        <div className="container mx-auto max-w-6xl flex justify-between">
          <div className="w-[40%]">
            <form className="flex flex-col justify-center w-full">
              <h2 className="font-['Cardo'] text-7xl font-bold text-center mb-8">
                Be updated!
              </h2>
              <input
                type="text"
                name="firstName"
                placeholder="First Name*"
                className="font-['Lato'] border-solid border-2 border-[#232323] rounded px-6 py-2 mb-4"
                required
              />
              <input
                type="text"
                name="lastName"
                placeholder="Last Name*"
                className="font-['Lato'] border-solid border-2 border-[#232323] rounded px-6 py-2 mb-4"
                required
              />
              <input
                type="text"
                name="subjext"
                placeholder="Email Subject*"
                className="font-['Lato'] border-solid border-2 border-[#232323] rounded px-6 py-2 mb-4"
                required
              />
              <textarea
                name="emailContent"
                placeholder="Write something here..."
                className="font-['Lato'] border-solid border-2 border-[#232323] rounded px-6 py-2 mb-4"
                rows={11}
              />
              <button type="Submit" className="bg-dark rounded text-white py-2">
                Send Email
              </button>
            </form>
          </div>
          <div className="w-[50%]">
            <Image src={Form} alt="" />
          </div>
        </div>
      </section>
      <footer className=" bg-[#c4c4c4] py-16">
        <div className="max-w-6xl mx-auto">
          <div className="flex justify-around mx-auto container">
            <h2 className="text-5xl font-bold font-['Cardo'] w-[20%]">
              My Log Travels
            </h2>
            <div className="w-[80%] mx-auto container">
              <div className="flex justify-around items-end mx-auto leading-loose">
                <div>
                  <h2 className="font-bold">Quick Links</h2>
                  <ul>
                    <Link href="#">
                      <li>Home</li>
                    </Link>
                    <Link href="#">
                      <li>About Us</li>
                    </Link>
                    <Link href="#">
                      <li>My Travel Logs</li>
                    </Link>
                  </ul>
                </div>
                <ul>
                  <Link href="#">
                    <li>Travels</li>
                  </Link>
                  <Link href="#">
                    <li>Promo Flights</li>
                  </Link>
                  <Link href="#">
                    <li>Travel Routes</li>
                  </Link>
                </ul>
                <ul>
                  <Link href="#">
                    <li>Recommendations</li>
                  </Link>
                  <Link href="#">
                    <li>Guides</li>
                  </Link>
                  <Link href="#">
                    <li>Blogs</li>
                  </Link>
                </ul>
                <ul>
                  <Link href="#">
                    <li>Mission Statement</li>
                  </Link>
                  <Link href="#">
                    <li>The Team</li>
                  </Link>
                  <Link href="#">
                    <li>Contact Us</li>
                  </Link>
                </ul>
              </div>
            </div>
          </div>
          <h2 className="text-center mt-16 font-['Lato'] box-border">
            2021 - 2022 My Log Travels. All Rights Reserved.
          </h2>
        </div>
      </footer>
    </>
  );
}
