import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import Hero from '../assets/hero-image.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Travel - Scrapbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container mx-auto max-w-6xl'>
        <nav className='flex justify-between py-10 m-0'>
          <ul className='flex space-x-16'>
            <Link href="#"><li className='hover:font-bold cursor-pointer'>Home</li></Link>
            <Link href="#"><li className='hover:font-bold cursor-pointer'>Guides</li></Link>
            <Link href="#"><li className='hover:font-bold cursor-pointer'>Flights</li></Link>
            <Link href="#"><li className='hover:font-bold cursor-pointer'>About</li></Link>
          </ul>
          <div className='border-2 border-solid border-black py-1 px-8 rounded font-bold'>
            <Link href="#">Contact Us</Link>
          </div>
        </nav>
        <section className='hero flex justify-between py-6'>
          <div className='w-2/5 pr-16 relative'>
            <h1 className='text-7xl font-["Cardo"] font-bold text-[#232323]'>Travel to<br/>your dream<br/>destination</h1>
            <p className='font-["Lato"] py-6 text-[#232323]'>Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum sus pendisse ultrices gravida. </p>
            <Link href="#"><p className='absolute bottom-2 py-2 px-8 text-[white] bg-[#232323] rounded w-[50%] text-center font-["Lato"] font-bold'>Reserve Ticket</p></Link>
          </div>
          <div>
            <Image src={Hero} alt="travel"/>
          </div>
        </section>
      </main>
      <section className='bg-[#232323] py-8'>
        <div className='w-1/3 m-0 mx-auto'>
          <h2 className='font-["Cardo"] text-[#e9e7e7] text-center font-bold text-5xl'>Create a memory to remember</h2>
          <p className='text-[#e9e7e7] text-center py-5 text-sm'>Lorem ipsum dolor sit amet, consectetur adipi scing elit, sed do ei usmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum sus pendisse ultrices gravida. </p>
          <Link href="#"><button className='text-[#e9e7e7] py-1.5 px-12 rounded border-2 border-solid font-["Lato"] mt-4 mb-0 ml-auto mr-auto block'>My Travel Logs</button></Link>
        </div>
      </section>
      <section>
        <div>

        </div>
      </section>
    </div>
  )
}
